
name: Go
on: [push]
jobs:
  Lint:
    runs-on: ubuntu-latest
    name: GolangCI Lint
    steps:
      - name: GolangCI-Lint Action
        uses: actions-contrib/golangci-lint@v0.1.0
        with:
          args: run -v ./...
